import Head from "next/head";
import LoginBar from "@/pages/login_bar";
import Menu from "@/pages/menu";

export default function About() {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginBar></LoginBar>
        <Menu></Menu>
        <div className="loginContainer">
          <div className="aboutLeft">
            <div className="blockAbout">
              <div>
                <h3>¿Quien Soy?</h3>
              </div>
              <div className="inputAbout">
                <div className="ocuparTodoDiv input"></div>
              </div>
              <div>
                <h3>Mi experencia</h3>
              </div>
              <div className="inputAbout">
                <div className="ocuparTodoDiv input"></div>
              </div>
              <div>
                <h3>Informaión de Contacto</h3>
              </div>
              <div className="inputAbout">
                <div className="ocuparTodoDiv input"></div>
              </div>
            </div>
          </div>
          <div>
            <div>
              <img src="./pages/Img1.jpg" alt="No se encontró" />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
