import Head from "next/head";
import LoginBar from "@/pages/login_bar";
import Menu from "@/pages/menu";
import Tarjetas from "@/components/tarjetas";
import Prismic from 'prismic-javascript';
import { useEffect, useState } from "react";

const apiEndpoint = "https://bryan-portafolio.cdn.prismic.io/api/v2/documents/search?ref=ZEtQZBEAACkAn1BG";
const accessToken = "MC5aRXRSSFJFQUFDZ0FuMU9H.77-977-977-9be-_vU1H77-9WW9Z77-977-9ZO-_ve-_vVXvv71m77-977-9EO-_vULvv73vv73vv73vv70XE--_ve-_vQ";


export default function Blog() {
  const client = Prismic.client(apiEndpoint, { accessToken });
  console.log(client);
  const [data, setData] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch(
          "https://bryan-portafolio.cdn.prismic.io/api/v2/documents/search?ref=ZEtQZBEAACkAn1BG"
        );
        const json = await response.json();
        setData(json);
        console.log(json)
      } catch (error) {
        console.error(error);
      }
    };

    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginBar></LoginBar>
        <Menu></Menu>
        <Tarjetas></Tarjetas>
      </div>
    </>
  );
}
