import Head from "next/head";
import LoginBar from "@/pages/login_bar";
import Menu from "@/pages/menu";
import Tarjetas from "@/components/tarjetas";


export default function Blog() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <LoginBar></LoginBar>
        <Menu></Menu>
        <Tarjetas></Tarjetas>
      </body>
    </>
  );
}
