import Head from "next/head";
import LoginBar from "@/pages/login_bar";
import Menu from "@/pages/menu";
import Tarjetas from "@/components/tarjetas";
import Prismic from 'prismic-javascript';
import { useEffect, useState } from "react";
import BlogContainer from "@/components/blog-container";

export default function Blog() {
  const [data, setData] = useState(null);
  const [publicaciones, setPublicaciones] = useState();
  const [estado, setEstado] = useState("false")

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        "https://bryan-portafolio.cdn.prismic.io/api/v2/documents/search?ref=ZEtQZBEAACkAn1BG"
      );
      const json = await response.json();
      setData(json["results"]);
      const elementos = json["results"].map((item) => (
        {
          id: item.id,
          title: item.data.title,
          description: item.data.description,
          cover: item.data.cover.url,
        }
      ));
      setPublicaciones(elementos);
    };
    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LoginBar></LoginBar>
        <Menu></Menu>
        <button type="" onClick={() =>
          setEstado("true")}>activa</button>
        {estado == "true" && <BlogContainer lista={publicaciones}></BlogContainer>}
      </div>
    </>
  );
}
