import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import LoginBar from '@/components/login_bar'
import Menu from '@/components/menu'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginBar></LoginBar>
      <Menu className="root2"></Menu>
      <style jsx>
        {`
          .root2 {
            display: flex,
            justify-content: space-around,
          }
        `}
      </style>
    </>
  )
}
