import LoginBar from "../login_bar";
import Menu from "../menu";
import Head from "next/head";
import { useRouter } from 'next/router';

export default function Post(){
    const router = useRouter();
    const { id } = router.query;
    return (
        <>
          <Head>
            <title>Education</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div>
            <LoginBar></LoginBar>
            <Menu></Menu>
            <div className="centrar">
            <h1>{id}</h1>
            </div>
          </div>
        </>
      );
}