import LoginBar from "../login_bar";
import Menu from "../menu";
import Head from "next/head";
import { useRouter } from 'next/router';
import { useState, useEffect } from "react";
import Publicacion from "@/components/publicacion";

export default function Post() {
    const router = useRouter();
    const [data, setData] = useState(null);
    const [publicaciones, setPublicaciones] = useState();
    const [estado, setEstado] = useState("false")

    useEffect(() => {
        const fetchData = async () => {
            const response = await fetch(
                "https://bryan-portafolio.cdn.prismic.io/api/v2/documents/search?ref=ZEtQZBEAACkAn1BG"
            );
            const json = await response.json();
            setData(json["results"]);
            const elementos = json["results"].map((item) => (
                {
                    id: item.id,
                    title: item.data.title,
                    description: item.data.description,
                    cover: item.data.cover.url,
                }
            ));
            setPublicaciones(elementos);
        };
        fetchData();
    }, []);
    const { id } = router.query;
    return (
        <>
            <Head>
                <title>Education</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <LoginBar></LoginBar>
                <Menu></Menu>
                <div className="centrar">
                    <button className="botones" type="" onClick={() => {
                        setEstado("true");
                        console.log(publicaciones)
                    }}>Leer {id}</button>
                </div>
                {estado == "true" && <Publicacion lista={publicaciones} publi={id}></Publicacion>}
            </div>
        </>
    );
}